### ISSUE TITLE
traditional mongolian/uyghur vertical script.

### ISSUE THREAD

**Issue by Popolon** [andreas-vox/ScribusCTL#13]
I just discovered this nice project for Scribus and would like to know if the Mongolian traditional, vertical script will be managed? I know there is at least montex for LaTeX, and I suppose that's the good time to think to this. Perhaps it will be to complex to integrate at the same time and it will be for later.

I try here to explain as far I know about the script and computer methods to write/display in the hope it can be for interest in futur for this writing in open source ecosystem:

In Mongolian (Khalkha, national language) that's referred by "mongol bichig" (Mongolian script) or "caagan tolgoi" (white head), that's often referred in Occident by "traditional Mongolian script" or by "Uyghur script", as it was first used by old Uyghur alphabet (today they use near from arabian/persian script). Uyghur alphabet is derivated itself from old Sogdian/Syriac/Manichaean scripts) will be managed. There are other name for variants (as for Oirat, another Mongolian language, Tungustic languages (Manchu, Evenk...) and probably (not sure at all) more sporadically by some turkish ( in Tuva, Kyrgyzstan, Kazakhstan or some Turkish minorities of China).

That's a very special case in scripts, only used by few millions people in desert area today, mainly for Mongolian and Tungusic languages in China, or a little less in Mongolia and Eastern Russia republics, as Cyrillic officially replaced this writing in this countries. It is still used for special occasions like decorative/artistic (as calligraphy) in Mongolia/eastern Russia republics but keep used in special cases (mainly artistic one). This is probably a big work on this part, as this is among the last fully vertical writing in the world (Chinese, Japanese and Korean are used horizontally from left to right on computer now).

There is an UTF-8 (U+18xx)/Mongolian range for this script, that I suppose can manage every variants including old uyghur. Generally tricks are used on website, like using JavaScript or writing horizontally and then rotate the text by 90° (this has some side effects, has some font are designed vertically from start some other horizontally to be rotated and software can't know if that's one or the other of the cases). The encoding has also some variants for websites, probably coming from pre-UTF ou proto-UTF eras. I for now meet 3 cases:
1. Simply using UTF-8 Mongolian range
2. Using actual UTF-8 basic Latin range + a conversion (called CMS if I'm not wrong). That's allow to write using west European keyboards without IME.
3. Using mixing ranges symbols and ascriptive conversion

Before trying the following sites (some embed fonts), installing montext (included in texlive-lang-cyrillic on ubuntu), can be a good method to have mongolian fonts installed.

Else, this site have nice calligraphy/computer fonts links (or you can search at (CMs Ulaanbaatar font around the web):
http://luc.devroye.org/mongolian.html

A website using JavaScript dedicated to writing Mongolian (give UTF-8 Mongolian range result that can be copy-pasted) (1st method):
http://www.unsen-sambar.com/

An Inner-Mongolia site (about Mongolian wrestling) using traditional script with 3rd method:
http://www.mongolbuh.com/publish/

The Cyrillic Mongolian Wiktionary use the 2nd method (Latin characters coding) to display traditional Mongol script:
https://mn.wiktionary.org/wiki/эмээл#Монгол бичиг

an english/.../mongolian dictionary that uses UTF8 Mongolian, only displayed horizontally,:
http://www.bolor-toli.com/dictionary/word?authenticity_token=dYB8Y%2Btq0NBtTbIPt1l2X6bYx8ISYv5T%2FUFHEVRj1T8%3D&selected_lang=4-1&search=монгол

Wikipedia does the same on Firefox by default, try to display vertically with Chromium, sometimes little SVG pictures of vertical text are used inside text to resolve all those issues in wikipedia. For example in this French version of Hohhot (The capital of Inner-Monglia), you can see how is broken in infobox at right (if you have the font) (horizontal font turned vertically, but still displayed horizontally) :
https://fr.wikipedia.org/wiki/Hohhot

This en/mn dictionary display CMS definition, UTF8 traditional Mongolian and Cyrillic Mongolian variants of the words :
https://www.istb.univie.ac.at/mongol/mng/cyr/verif2.php

You can see here, than Latin characters are rotated 90° too (see the next link, I seen prints in Inner-Mongolia that look like this too) some time you have some foreign script turned left, some other turned right, that is probably good for neck exercises ;) ).
http://www.mongolbuh.com/publish/zoog/content/2014102110311212109.htm

So I believe today the most simple method is using Mongolian and wrote vertically (with probably an option to rotate or not characters ?) LaTеX could be a good reference. There is a specialized module called "montex – Mongolian LaTeX" (when searching for Mongolian, other packages are for cyrillic Mongolian script, that add some chars to the Russian or Bulgarian Cyrillic):
http://www.ctan.org/pkg/montex

A document about proposal to include birga (punctuation/head marks) symbols on UTF-8 that should contain some refs:
http://www.unicode.org/L2/L2014/14067-mongolian.pdf

Some tools exists for Android or iOS, I tried it on a rooted Samsung, but I had to wipe system, as Samsung interface doesn't manage at all vertical text, some buttons could not be pressed anymore, as far away from the screen display :D, so if someone want to get a try, save your data before... 
http://www.mongolfont.com/
http://blog.163.com/baoshijie_2212/blog/static/1119047192012103024359913/

Some pictures of Mongolian writing, beside English and Chinese on street/road panels in Inner-Mongolia:
https://commons.wikimedia.org/wiki/Category:Signs_in_Mongolian_script

As references (for the fun, probably interesting for archaeology/history purposes) about the origins of this writing :
https://en.wikipedia.org/wiki/Old_Uyghur_alphabet
https://en.wikipedia.org/wiki/Sogdian_alphabet
https://en.wikipedia.org/wiki/Manichaean_alphabet
https://en.wikipedia.org/wiki/Syriac_alphabet

**Comment by KrasnayaPloshchad** [comment]
You can also try to copy following texts into Google Search to get some samples:

`site:hb.mgyxw.net filetype:pdf`

**Comment by luzpaz** [comment]
Slightly off-topic but relevant:
Please consider volunteering to help translate Scribus in to Mongolian...  our crowdsourced translation effort is going on here https://www.transifex.com/scribus/scribus/ 
Thanks in advance!

**Comment by luzpaz** [comment]
Posted to Scribus bugtracker 
https://bugs.scribus.net/view.php?id=13849

**Comment by luzpaz** [comment]
Please continue thread in the Scribus bugtracker. 
Also efforts to get Right-to-Left languages working are happening in https://github.com/HOST-Oman/scribus but vertical text is still not supported as of this date.

**Comment by luzpaz** [comment]
@Popolon Please upload tests to https://github.com/scribusproject/test-samples
