### ISSUE TITLE
Persian Language test in 1.5.1 svn

### ISSUE THREAD

**Issue by msm1365** [andreas-vox/ScribusCTL#19]
I try to test Persian ( Farsi ) language in 1.5.1svn, but it is still unclear. I install 1.5.1svn on fedora from :

https://copr.fedoraproject.org/coprs/luya/scribus-unstable/

![screenshot from 2016-01-14 09-24-00](https://cloud.githubusercontent.com/assets/12663667/12316911/36cba754-baa1-11e5-8815-1be016f125b2.png)

**Comment by luzpaz** [comment]
The repo you would need to download and test ScribusCTL from is **this** repo, https://github.com/andreas-vox/ScribusCTL 

The code in this repo is _still_ being constructed. Keep an eye on the development in https://github.com/andreas-vox/ScribusCTL/pulls and also on the Scribus Developer Mailing List http://lists.scribus.net/pipermail/scribus-dev/

I've added you to a list of potential testers in https://github.com/andreas-vox/ScribusCTL/issues/14 so once things are 'green light' then I'll ping you.

**Comment by msm1365** [comment]
ok, I will speak with repository and I will notice results. I test scribusctl in Persian language ( Iran, Afghanistan and Tajikistan ).

**Comment by luzpaz** [comment]
Thanks @msm1365

**Comment by luzpaz** [comment]
FYI, @msm1365 you can also contribute translations for those languages if you were so inclined. Check out https://www.transifex.com/scribus/scribus

**Comment by luzpaz** [comment]
@msm1365 can you provide us a test document of different Farsi scripts in Scribus for us to test?

**Comment by msm1365** [comment]
@luzpaz 

![screenshot from 2016-03-25 05-05-34](https://cloud.githubusercontent.com/assets/12663667/14035053/4842a6ee-f247-11e5-9c8b-7b8767d79039.png)
