### ISSUE TITLE
build .spec file for rpm package

### ISSUE THREAD

**Issue by msm1365** [andreas-vox/ScribusCTL#20]
Hi,

I now building a .spec file for compiling and create scribusctl.rpm for use in fedora.

But I have a problem, I can't complete .spec file. .spec file need two option :

1- BuildRequires
2- Requires

more about options :

BuildRequires: A comma-separated list of packages required for building (compiling) the program. This field can be (and is commonly) repeated on multiple lines. These dependencies are not automatically determined, so you need to include everything needed to build the program. Some common packages can be omitted, such as gcc. You can specify a minimum version if necessary (e.g. "ocaml >= 3.08"). If you need the file /EGGS, determine the package that owns it by running "rpm -qf /EGGS". If you need the program EGGS, determine the package that owns it by running "rpm -qf `which EGGS`". Keep dependencies to a minimum (e.g. use sed instead of perl if you don't really need perl's abilities), but beware that some applications permanently disable functions if the associated dependency is not present; in those cases you may need to include the additional packages. The Package-x-generic-16.pngauto-buildrequires package may be helpful.

Requires: A comma-separate list of packages that are required when the program is installed. Note that the BuildRequires tag lists what is required to build the binary RPM, while the Requires tag lists what is required when installing/running the program; a package may be in one list or in both. In many cases, rpmbuild automatically detects dependencies so the Requires tag is not always necessary. However, you may wish to highlight some specific packages as being required, or they may not be automatically detected.

Please help me to complete .spec file.

**Comment by luzpaz** [comment]
@msm1365 the plans for ScribusCTL is that it will be merged in to Scribus trunk. Perhaps a better idea is to setup a working RPM for Scribus trunk? See http://bugs.scribus.net/view.php?id=13341 
plinnell is the person to talk to. 

If you want to build ScribusCTL I'd wait till the 2 pending PRs (https://github.com/andreas-vox/ScribusCTL/pulls) are merged

**Comment by msm1365** [comment]
unfortunately i couldn't build rpm package for fedora. but a spec file was made, I'd be happy if anybody build rpm package and upload it to project repository at below links.

https://luya.fedorapeople.org/packages/SPECS/scribusctl.spec
https://copr.fedorainfracloud.org/coprs/luya/scribus-unstable/

**Comment by luzpaz** [comment]
Heads up: as per http://lists.scribus.net/pipermail/scribus-dev/2016-January/002884.html
andreas-vox will sync ScribusCTL with scribusproject/scribus (master) repo this weekend, hopefully.

**Comment by msm1365** [comment]
@luzpaz @andreas-vox 
passed due date but there is no news!!!

I tried to build scribusCTL repository in fedora copr, but I did not succeed.

![screenshot from 2016-02-11 11-19-37](https://cloud.githubusercontent.com/assets/12663667/12971578/db9a2de8-d0b1-11e5-9027-1fe2e3666178.png)
